config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-jade-dogfish.sh
        container: qc.acc_sickly-violet-rottweiler
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cyan-seahorse.sh
        container: qc.doc_thirsty-puce-lobster
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-flax-ibis.sh
        container: qc.doc_lovely-gamboge-quoll
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-fuchsia-snail.sh
        container: qc.doc_wheezy-cobalt-angora
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-coral-meerkat.sh
        container: qc.lic_lovely-vermilion-wolfhound
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sapphire-chameleon.sh
        container: qc.met_cloudy-dandelion-eagle
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-brown-crab.sh
        container: qc.sty_lousy-viridian-rabbit
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-mustard-caterpillar.sh
        container: qc.sty_chewy-viridian-snake
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-seashell-bison.sh
        container: qc.ver_muzzy-coral-blue
timeout: 5400
