config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-taupe-sheep.sh
        container: qc.acc_hazy-wheat-rattlesnake
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-gold-audemer.sh
        container: qc.doc_leaky-cornflower-chamois
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-gamboge-russel.sh
        container: qc.doc_wheezy-salmon-emu
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-thistle-stingray.sh
        container: qc.lic_silly-teal-iguana
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-burgundy-gerbil.sh
        container: qc.ver_squeaky-ruby-caiman
timeout: 5400
