config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-tan-vulture.sh
        container: qc.acc_scanty-bistre-ocelot
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-beige-bear.sh
        container: qc.doc_gamy-heliotrope-vole
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-violet-spaniel.sh
        container: qc.doc_frumpy-emerald-wolf
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ivory-jaguar.sh
        container: qc.doc_dorky-cerise-ibis
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-copper-nightingale.sh
        container: qc.lic_slimy-beige-penguin
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-rose-sloth.sh
        container: qc.met_cranky-xanthic-wolfhound
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-flax-antelope.sh
        container: qc.sty_clammy-wheat-hyrax
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-scarlet-tarantula.sh
        container: qc.sty_beady-amaranth-boar
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-chestnut-grouse.sh
        container: qc.ver_grumpy-lemon-monster
timeout: 5400
