config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-auburn-tortoise.sh
        container: qc.acc_cranky-russet-axolotl
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-yellow-sheep.sh
        container: qc.doc_shaky-sapphire-sloth
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-blue-devil.sh
        container: qc.doc_grumpy-auburn-cougar
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cerise-quoll.sh
        container: qc.doc_lousy-asparagus-moth
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-wheat-angelfish.sh
        container: qc.lic_lanky-denim-squirrel
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.beady-flax-fly.sh
        container: qc.met_muzzy-amaranth-seal
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-beige-eagle.sh
        container: qc.sty_homely-taupe-eagle
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-burgundy-kingfisher.sh
        container: qc.sty_slaphappy-taupe-gecko
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-plum-spaniel.sh
        container: qc.ver_shabby-asparagus-lobster
timeout: 5400
