config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-malachite-bandicoot.sh
        container: qc.acc_squirrely-asparagus-sponge
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-gold-iguana.sh
        container: qc.doc_sunny-dandelion-neanderthal
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-white-dane.sh
        container: qc.doc_beady-dandelion-centipede
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-brass-balinese.sh
        container: qc.doc_fuzzy-carmine-dhole
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-magenta-turkey.sh
        container: qc.lic_homely-aquamarine-macaw
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-mustard-quokka.sh
        container: qc.met_frumpy-blue-affenpinscher
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-zucchini-lemming.sh
        container: qc.sty_woozy-coral-vole
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cardinal-spoonbill.sh
        container: qc.sty_crabby-buff-raccoon
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-buff-fly.sh
        container: qc.ver_tasty-amethyst-guppy
timeout: 5400
