config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-pink-lobster.sh
        container: qc.acc_skanky-turquoise-toucan
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-goldenrod-discus.sh
        container: qc.doc_tacky-rose-cattle
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-dandelion-buffalo.sh
        container: qc.doc_scummy-aqua-beaver
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-asparagus-hyena.sh
        container: qc.doc_gummy-seashell-shark
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cobalt-leopard.sh
        container: qc.lic_dorky-persimmon-hamster
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-tangerine-axolotl.sh
        container: qc.met_gloppy-peach-eagle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-alizarin-sloth.sh
        container: qc.sty_bluesy-fuchsia-hippopotamus
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-magenta-cockroach.sh
        container: qc.sty_snippy-bronze-terrier
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-flax-gecko.sh
        container: qc.ver_shaggy-ultramarine-opossum
timeout: 5400
