config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-eggplant-woodpecker.sh
        container: qc.acc_wiggy-rust-mayfly
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cinnamon-panda.sh
        container: qc.doc_fuzzy-teal-maltese
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-salmon-heron.sh
        container: qc.doc_zippy-myrtle-monster
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ultramarine-seal.sh
        container: qc.doc_muggy-rose-hedgehog
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-auburn-cassowary.sh
        container: qc.lic_snazzy-lemon-ragdoll
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ready-celadon-fowl.sh
        container: qc.met_pokey-jade-coati
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-violet-lynx.sh
        container: qc.sty_boozy-sangria-fly
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-orange-saola.sh
        container: qc.sty_whiny-persimmon-buffalo
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-burgundy-corgi.sh
        container: qc.ver_lumpy-mauve-mule
timeout: 5400
