config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-brass-beagle.sh
        container: qc.acc_surly-cinnabar-dingo
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-teal-bloodhound.sh
        container: qc.doc_woozy-lime-macaque
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-charcoal-urchin.sh
        container: qc.doc_sickly-peach-frigatebird
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lilac-sloth.sh
        container: qc.doc_gamy-lavender-echidna
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-coral-akita.sh
        container: qc.lic_wheezy-xanthic-slug
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-peach-dolphin.sh
        container: qc.met_greasy-peach-javanese
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-mustard-toad.sh
        container: qc.sty_pokey-salmon-otter
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-charcoal-javanese.sh
        container: qc.sty_sleazy-blue-turtle
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-periwinkle-tarantula.sh
        container: qc.ver_leaky-ultramarine-discus
timeout: 5400
