config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-peach-skunk.sh
        container: qc.acc_jumpy-tomato-bat
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ivory-kakapo.sh
        container: qc.doc_flaky-cinnabar-dachshund
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-burgundy-warthog.sh
        container: qc.doc_fuzzy-olivine-seal
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-copper-ant.sh
        container: qc.doc_chummy-lemon-spoonbill
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-linen-collie.sh
        container: qc.lic_wiggy-silver-chipmunk
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.silly-malachite-audemer.sh
        container: qc.met_gloppy-cerise-echidna
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-azure-insect.sh
        container: qc.sty_flimsy-rose-mayfly
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-apricot-kiwi.sh
        container: qc.sty_droopy-sepia-weasel
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-sapphire-frog.sh
        container: qc.ver_freaky-ultramarine-snake
timeout: 5400
