config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-zucchini-retriever.sh
        container: qc.acc_skanky-green-ferret
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-pink-woodlouse.sh
        container: qc.doc_hilly-peach-mandrill
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-periwinkle-sloth.sh
        container: qc.doc_freaky-brown-barb
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-black-macaque.sh
        container: qc.doc_skanky-cream-setter
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-plum-husky.sh
        container: qc.lic_grumpy-mauve-panda
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-amber-albatross.sh
        container: qc.met_muzzy-heliotrope-eagle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-charcoal-cassowary.sh
        container: qc.sty_frumpy-alizarin-chimpanzee
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-corn-chameleon.sh
        container: qc.sty_skanky-maroon-bee
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-silver-chicken.sh
        container: qc.ver_freaky-linen-budgerigar
timeout: 5400
