config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-auburn-fish.sh
        container: qc.acc_homely-heliotrope-greyhound
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cobalt-orangutan.sh
        container: qc.doc_fuzzy-buff-hornet
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-white-havanese.sh
        container: qc.doc_beady-cobalt-wolverine
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-taupe-mammoth.sh
        container: qc.doc_crabby-orchid-saola
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-myrtle-caterpillar.sh
        container: qc.lic_whiny-corn-cuscus
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-champagne-ostrich.sh
        container: qc.met_chummy-tangerine-seal
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lavender-armadillo.sh
        container: qc.sty_stealthy-silver-centipede
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-apricot-ladybird.sh
        container: qc.sty_muzzy-chartreuse-barracuda
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-yellow-coral.sh
        container: qc.ver_bumpy-chestnut-butterfly
timeout: 5400
