config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-orchid-tarsier.sh
        container: qc.acc_scummy-bistre-bee
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-yellow-bullfrog.sh
        container: qc.doc_stuffy-magenta-bracke
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ruby-bracke.sh
        container: qc.doc_leaky-brown-blue
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-xanthic-cassowary.sh
        container: qc.doc_muggy-turquoise-audemer
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-yellow-crocodile.sh
        container: qc.lic_freaky-tomato-cheetah
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-taupe-ladybird.sh
        container: qc.met_craggy-black-angora
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ivory-devil.sh
        container: qc.sty_leaky-cornflower-lynx
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-jade-alligator.sh
        container: qc.sty_bumpy-scarlet-toad
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-purple-avocet.sh
        container: qc.ver_trippy-buff-crab
timeout: 5400
