config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-purple-lynx.sh
        container: qc.acc_shaky-celadon-monkey
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-linen-opossum.sh
        container: qc.doc_breezy-persimmon-urchin
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cornflower-lynx.sh
        container: qc.doc_trippy-yellow-echidna
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-celadon-kudu.sh
        container: qc.doc_flimsy-viridian-forest
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-ochre-tuatara.sh
        container: qc.lic_blurry-purple-zebra
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-copper-wolfhound.sh
        container: qc.met_tacky-persimmon-hornet
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-emerald-neanderthal.sh
        container: qc.sty_lanky-champagne-foxhound
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cardinal-retriever.sh
        container: qc.sty_flabby-asparagus-argentino
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-gamboge-akbash.sh
        container: qc.ver_dorky-asparagus-swan
timeout: 5400
