config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-crimson-whippet.sh
        container: qc.acc_droopy-saffron-saola
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-turquoise-russel.sh
        container: qc.doc_cloudy-brown-orangutan
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-apricot-wasp.sh
        container: qc.doc_slaphappy-auburn-elephant
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-crimson-slug.sh
        container: qc.doc_grumpy-magenta-axolotl
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-white-chamois.sh
        container: qc.lic_sleazy-silver-akbash
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-salmon-orangutan.sh
        container: qc.met_sunny-russet-bear
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-magenta-mandrill.sh
        container: qc.sty_woolly-wisteria-whippet
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-azure-moorhen.sh
        container: qc.sty_zippy-cinnabar-eleuth
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-ivory-catfish.sh
        container: qc.ver_skinny-purple-ant
timeout: 5400
