config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-harlequin-gerbil.sh
        container: qc.acc_stinky-smalt-bongo
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-chocolate-neanderthal.sh
        container: qc.doc_nippy-emerald-terrier
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-brown-lemur.sh
        container: qc.doc_wiggy-scarlet-tarantula
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-brass-russel.sh
        container: qc.doc_baggy-apricot-forest
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cardinal-chinook.sh
        container: qc.lic_seedy-viridian-lizard
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-brown-opossum.sh
        container: qc.met_stuffy-cinnabar-tamarin
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lime-tortoise.sh
        container: qc.sty_craggy-crimson-serval
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-firebrick-echidna.sh
        container: qc.sty_skanky-amaranth-reindeer
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cinnamon-wasp.sh
        container: qc.ver_snappy-magnolia-owl
timeout: 5400
