config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-ivory-russel.sh
        container: qc.acc_cozy-magnolia-zonkey
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-crimson-angora.sh
        container: qc.doc_silly-ultramarine-boar
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-olive-seahorse.sh
        container: qc.doc_fuzzy-coral-starfish
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-eggplant-collie.sh
        container: qc.doc_snippy-olivine-woodpecker
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-charcoal-mole.sh
        container: qc.lic_craggy-gold-seal
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cornflower-foxhound.sh
        container: qc.met_trippy-pumpkin-sparrow
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-malachite-goose.sh
        container: qc.sty_whiny-turquoise-chow
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cerise-baboon.sh
        container: qc.sty_ready-dandelion-ladybird
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-carmine-chamois.sh
        container: qc.ver_blurry-russet-skunk
timeout: 5400
