config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-lilac-bongo.sh
        container: qc.acc_cozy-tangerine-birman
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-eggplant-barb.sh
        container: qc.doc_lousy-peach-frigatebird
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-blue-coral.sh
        container: qc.doc_clammy-burgundy-cichlid
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-smalt-ladybird.sh
        container: qc.doc_crappy-sepia-guppy
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-goldenrod-emu.sh
        container: qc.lic_clammy-eggplant-giraffe
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-chocolate-saola.sh
        container: qc.met_geeky-cinnabar-wolverine
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-taupe-centipede.sh
        container: qc.sty_lousy-alizarin-macaw
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-heliotrope-okapi.sh
        container: qc.sty_chewy-yellow-budgerigar
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-viridian-wasp.sh
        container: qc.ver_lovely-buff-monster
timeout: 5400
