config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-rose-abyssinian.sh
        container: qc.acc_pokey-taupe-flamingo
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-white-hummingbird.sh
        container: qc.doc_trippy-zucchini-mammoth
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cinnamon-swan.sh
        container: qc.doc_snippy-saffron-akita
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chartreuse-falcon.sh
        container: qc.doc_cloudy-apricot-mist
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-sangria-caiman.sh
        container: qc.lic_droopy-myrtle-monkey
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-chestnut-shrew.sh
        container: qc.met_flabby-periwinkle-catfish
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-burgundy-balinese.sh
        container: qc.sty_ready-brass-giraffe
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-chestnut-avocet.sh
        container: qc.sty_fuzzy-burgundy-havanese
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-burgundy-fly.sh
        container: qc.ver_wiggy-bistre-lemming
timeout: 5400
