config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-olive-affenpinscher.sh
        container: qc.acc_whiny-olivine-wolfhound
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-maroon-dormouse.sh
        container: qc.doc_tasty-green-kakapo
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-mustard-bear.sh
        container: qc.doc_sunny-rust-sheep
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-bronze-mayfly.sh
        container: qc.doc_homely-yellow-loon
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-scarlet-duck.sh
        container: qc.lic_nerdy-brass-grouse
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homely-pumpkin-bordeaux.sh
        container: qc.met_wiggy-chestnut-whippet
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amethyst-anteater.sh
        container: qc.sty_flimsy-teal-sparrow
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lemon-mammoth.sh
        container: qc.sty_slaphappy-burgundy-dragon
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-amethyst-tarantula.sh
        container: qc.ver_pokey-olive-devil
timeout: 5400
