config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sepia-dunker.sh
        container: qc.acc_queasy-dandelion-angelfish
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-xanthic-ibis.sh
        container: qc.doc_grumpy-chestnut-jaguar
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-viridian-grasshopper.sh
        container: qc.doc_frumpy-zucchini-schnauzer
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-apricot-wrasse.sh
        container: qc.doc_sickly-rose-yak
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-mauve-flamingo.sh
        container: qc.lic_seedy-amaranth-mastiff
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-brown-moose.sh
        container: qc.met_ready-saffron-urchin
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-peach-akita.sh
        container: qc.sty_hasty-pink-zonkey
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-pumpkin-chameleon.sh
        container: qc.sty_messy-chartreuse-emu
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-pink-harrier.sh
        container: qc.ver_bumpy-chartreuse-mau
timeout: 5400
