config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-fuchsia-retriever.sh
        container: qc.acc_randy-white-corgi
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-burgundy-birman.sh
        container: qc.doc_muzzy-eggplant-spider
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-heliotrope-raccoon.sh
        container: qc.doc_woozy-yellow-goat
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-asparagus-earwig.sh
        container: qc.doc_nippy-brass-flounder
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-russet-shrew.sh
        container: qc.lic_sleepy-amaranth-drever
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.surly-mustard-mongoose.sh
        container: qc.met_leaky-thistle-horse
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-platinum-avocet.sh
        container: qc.sty_sunny-tangerine-newfoundland
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pear-manatee.sh
        container: qc.sty_zippy-orchid-beetle
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-salmon-horse.sh
        container: qc.ver_blurry-plum-macaw
timeout: 5400
