config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-linen-chihuahua.sh
        container: qc.acc_cranky-goldenrod-moorhen
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cornflower-badger.sh
        container: qc.doc_sunny-sangria-whippet
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-sangria-husky.sh
        container: qc.doc_tacky-lime-moose
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ruby-butterfly.sh
        container: qc.doc_woolly-cerulean-setter
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-persimmon-tiger.sh
        container: qc.lic_wimpy-magenta-barnacle
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-champagne-chamois.sh
        container: qc.met_stealthy-amethyst-scorpion
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-jade-otter.sh
        container: qc.sty_gummy-cardinal-giraffe
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-teal-echidna.sh
        container: qc.sty_nippy-chartreuse-maltese
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ecru-dog.sh
        container: qc.ver_lovely-corn-penguin
timeout: 5400
