config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-khaki-shrew.sh
        container: qc.acc_gamy-beige-ibis
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-scarlet-fousek.sh
        container: qc.doc_randy-charcoal-mau
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-lemon-dhole.sh
        container: qc.doc_flaky-russet-boar
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ochre-hyena.sh
        container: qc.doc_squirrely-aquamarine-horse
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-thistle-fly.sh
        container: qc.lic_gimpy-aquamarine-caracal
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-grey-oyster.sh
        container: qc.met_woozy-cobalt-reindeer
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-harlequin-yak.sh
        container: qc.sty_lanky-charcoal-snake
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-lemon-rhinoceros.sh
        container: qc.sty_queasy-flax-chinchilla
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-peach-shrew.sh
        container: qc.ver_shaggy-scarlet-neanderthal
timeout: 5400
