config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cornflower-dalmatian.sh
        container: qc.acc_messy-brass-kakapo
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-white-wombat.sh
        container: qc.doc_fuzzy-tomato-frise
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-orange-snake.sh
        container: qc.doc_geeky-champagne-worm
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cream-badger.sh
        container: qc.doc_baggy-taupe-chinook
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-goldenrod-whale.sh
        container: qc.lic_beady-firebrick-nightingale
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lemon-fish.sh
        container: qc.met_smelly-copper-horse
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-thistle-shrimp.sh
        container: qc.sty_sickly-bistre-mole
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-harlequin-hornet.sh
        container: qc.sty_bumpy-seashell-corgi
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-lilac-bordeaux.sh
        container: qc.ver_homey-scarlet-hedgehog
timeout: 5400
