config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-bistre-cattle.sh
        container: qc.acc_muzzy-pink-lionfish
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-russet-manatee.sh
        container: qc.doc_tacky-magenta-greyhound
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-apricot-hedgehog.sh
        container: qc.doc_gamy-linen-alligator
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-plum-otter.sh
        container: qc.doc_flaky-pumpkin-cassowary
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ecru-tuatara.sh
        container: qc.lic_muggy-alizarin-dugong
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-ecru-buffalo.sh
        container: qc.met_hasty-eggplant-nightingale
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-burgundy-crocodile.sh
        container: qc.sty_bluesy-maroon-boar
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cinnabar-robin.sh
        container: qc.sty_cloudy-puce-grouse
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-eggplant-mist.sh
        container: qc.ver_freaky-brass-dragonfly
timeout: 5400
