config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-seashell-angelfish.sh
        container: qc.acc_sleepy-salmon-moth
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-maroon-tetra.sh
        container: qc.doc_messy-white-millipede
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-peach-stingray.sh
        container: qc.doc_fuzzy-ecru-angelfish
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-grey-llama.sh
        container: qc.doc_flabby-mustard-goat
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-apricot-badger.sh
        container: qc.lic_muggy-ivory-cattle
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ecru-shark.sh
        container: qc.met_gamy-ecru-ray
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-orchid-wombat.sh
        container: qc.sty_grumpy-turquoise-camel
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-dandelion-ostrich.sh
        container: qc.sty_pretty-orchid-dragon
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-wisteria-coral.sh
        container: qc.ver_hasty-charcoal-vulture
timeout: 5400
