config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-amethyst-eel.sh
        container: qc.acc_sleazy-rust-starfish
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-magenta-turkey.sh
        container: qc.doc_pasty-chartreuse-zebra
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-tangerine-mandrill.sh
        container: qc.doc_sleazy-brass-fox
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-sangria-jaguar.sh
        container: qc.doc_tasty-cobalt-kudu
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-magnolia-mist.sh
        container: qc.lic_snazzy-pumpkin-cheetah
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-silver-gorilla.sh
        container: qc.met_sunny-wheat-sponge
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-emerald-tang.sh
        container: qc.sty_skanky-pumpkin-goose
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-emerald-pinscher.sh
        container: qc.sty_cranky-crimson-gar
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-periwinkle-snake.sh
        container: qc.ver_sleazy-lemon-quetzal
timeout: 5400
