config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-myrtle-markhor.sh
        container: qc.acc_crappy-cerulean-woodlouse
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-wisteria-bear.sh
        container: qc.doc_silly-black-urchin
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-aqua-antelope.sh
        container: qc.doc_blurry-vermilion-caracal
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-apricot-ostrich.sh
        container: qc.doc_sleazy-puce-skunk
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-alizarin-dhole.sh
        container: qc.lic_beady-rose-newfoundland
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-pink-bulldog.sh
        container: qc.met_sleazy-chartreuse-javanese
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-dandelion-rat.sh
        container: qc.sty_stinky-cerulean-spitz
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-fuchsia-hound.sh
        container: qc.sty_scaly-silver-mule
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-silver-sponge.sh
        container: qc.ver_frumpy-periwinkle-cuttlefish
timeout: 5400
