config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-amethyst-clam.sh
        container: qc.acc_sunny-charcoal-grouse
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ivory-nightingale.sh
        container: qc.doc_freaky-puce-vulture
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-ultramarine-falcon.sh
        container: qc.doc_jumpy-thistle-llama
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-red-catfish.sh
        container: qc.doc_shaky-rose-giraffe
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-myrtle-rhinoceros.sh
        container: qc.lic_whiny-crimson-tortoise
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.randy-xanthic-spitz.sh
        container: qc.met_messy-vermilion-bison
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-eggplant-emu.sh
        container: qc.sty_baggy-indigo-ray
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-wisteria-chin.sh
        container: qc.sty_crabby-cream-mammoth
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-razzmatazz-retriever.sh
        container: qc.ver_baggy-cream-lobster
timeout: 5400
