config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-beige-hyena.sh
        container: qc.acc_tasty-crimson-clam
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ivory-hyena.sh
        container: qc.doc_cranky-lavender-chamois
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-peach-gecko.sh
        container: qc.doc_cloudy-cerulean-jackal
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-emerald-bison.sh
        container: qc.doc_shaggy-gamboge-newfoundland
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-razzmatazz-javanese.sh
        container: qc.lic_slaphappy-platinum-magpie
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-eggplant-snail.sh
        container: qc.met_flaky-buff-octopus
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-corn-pig.sh
        container: qc.sty_silly-lemon-centipede
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-firebrick-iguana.sh
        container: qc.sty_muggy-alizarin-bulldog
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-beige-bloodhound.sh
        container: qc.ver_squeaky-persimmon-lynx
timeout: 5400
