config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-seashell-jellyfish.sh
        container: qc.acc_foggy-aquamarine-whippet
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-rose-capuchin.sh
        container: qc.doc_wiggy-heliotrope-sheep
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cinnabar-lemur.sh
        container: qc.doc_dorky-plum-squid
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-asparagus-bracke.sh
        container: qc.doc_sickly-indigo-hyena
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-rust-spider.sh
        container: qc.lic_scanty-teal-salamander
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-myrtle-monkey.sh
        container: qc.met_slimy-olivine-giraffe
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-indigo-starfish.sh
        container: qc.sty_shabby-black-saola
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-azure-fox.sh
        container: qc.sty_boozy-lilac-robin
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-turquoise-grouse.sh
        container: qc.ver_fuzzy-champagne-chimpanzee
timeout: 5400
