config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-firebrick-vulture.sh
        container: qc.acc_snoopy-yellow-audemer
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-burgundy-turtle.sh
        container: qc.doc_squirrely-burgundy-fox
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-apricot-woodpecker.sh
        container: qc.doc_pretty-rose-wolf
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-chestnut-shark.sh
        container: qc.doc_woolly-puce-fly
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-beige-zonkey.sh
        container: qc.lic_tasty-rust-frog
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lavender-slug.sh
        container: qc.met_trippy-sapphire-impala
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-wisteria-coyote.sh
        container: qc.sty_geeky-cobalt-dunker
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cinnabar-panda.sh
        container: qc.sty_wheezy-harlequin-crane
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-sepia-angora.sh
        container: qc.ver_nerdy-wheat-corgi
timeout: 5400
