config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-wisteria-cuscus.sh
        container: qc.acc_greasy-olivine-tang
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-brass-tarsier.sh
        container: qc.doc_homely-turquoise-fowl
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cobalt-eagle.sh
        container: qc.doc_droopy-pink-moose
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-periwinkle-dhole.sh
        container: qc.doc_trippy-eggplant-chihuahua
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-tan-rottweiler.sh
        container: qc.lic_droopy-tomato-liger
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-charcoal-havanese.sh
        container: qc.met_baggy-coral-corgi
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cream-eleuth.sh
        container: qc.sty_trippy-viridian-toucan
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-apricot-mau.sh
        container: qc.sty_snazzy-tomato-swan
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pumpkin-numbat.sh
        container: qc.ver_lumpy-lavender-kingfisher
timeout: 5400
