config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-razzmatazz-birman.sh
        container: qc.acc_crappy-platinum-dunker
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-sepia-angora.sh
        container: qc.doc_craggy-mauve-meerkat
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-razzmatazz-dachshund.sh
        container: qc.doc_baggy-yellow-drever
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-beige-slug.sh
        container: qc.doc_sloppy-peach-falcon
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-periwinkle-slug.sh
        container: qc.lic_seedy-cinnabar-mayfly
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-platinum-starfish.sh
        container: qc.met_breezy-denim-cougar
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-persimmon-koala.sh
        container: qc.sty_scummy-olivine-wallaby
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-charcoal-alligator.sh
        container: qc.sty_craggy-denim-guppy
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-azure-axolotl.sh
        container: qc.ver_leaky-sepia-jackal
timeout: 5400
