config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-periwinkle-zonkey.sh
        container: qc.acc_greasy-viridian-tapir
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-ecru-mau.sh
        container: qc.doc_nerdy-apricot-collie
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-brown-cassowary.sh
        container: qc.doc_nerdy-thistle-eel
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-collie.sh
        container: qc.doc_gummy-russet-hyrax
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cobalt-meerkat.sh
        container: qc.lic_snoopy-thistle-shark
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-peach-elephant.sh
        container: qc.met_zippy-brown-mandrill
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-peach-paradise.sh
        container: qc.sty_cloudy-tomato-cassowary
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-platinum-zebra.sh
        container: qc.sty_chummy-razzmatazz-ostrich
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-platinum-hare.sh
        container: qc.ver_muggy-heliotrope-salamander
timeout: 5400
