config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cyan-bear.sh
        container: qc.acc_sunny-wheat-woodlouse
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cerise-kangaroo.sh
        container: qc.doc_bumpy-cyan-corgi
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-pear-jaguar.sh
        container: qc.doc_woozy-russet-falcon
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cerulean-tzu.sh
        container: qc.doc_grumpy-chartreuse-bloodhound
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-harlequin-mole.sh
        container: qc.lic_thirsty-salmon-hippopotamus
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-olive-macaque.sh
        container: qc.met_bluesy-pink-bracke
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-amaranth-quail.sh
        container: qc.sty_flabby-cream-hare
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-corn-ocelot.sh
        container: qc.sty_greasy-lime-wildebeest
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-xanthic-mist.sh
        container: qc.ver_flimsy-aqua-dugong
timeout: 5400
