config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-peach-dragon.sh
        container: qc.acc_lanky-flax-insect
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-peach-wildebeest.sh
        container: qc.doc_randy-lemon-llama
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-pink-bison.sh
        container: qc.doc_geeky-silver-frise
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-orange-crane.sh
        container: qc.doc_wiggy-puce-yak
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-chestnut-hedgehog.sh
        container: qc.lic_pasty-harlequin-penguin
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-emerald-fox.sh
        container: qc.met_wiggy-copper-lizard
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-champagne-dhole.sh
        container: qc.sty_woolly-smalt-eel
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-azure-civet.sh
        container: qc.sty_foggy-sepia-seahorse
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-vermilion-dollar.sh
        container: qc.ver_silly-cornflower-mongoose
timeout: 5400
