config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-auburn-warthog.sh
        container: qc.acc_goopy-emerald-bobcat
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-orange-seal.sh
        container: qc.doc_cloudy-magnolia-spider
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lilac-lion.sh
        container: qc.doc_chewy-cardinal-serval
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cerise-bracke.sh
        container: qc.doc_smelly-salmon-fish
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-corn-lion.sh
        container: qc.lic_geeky-ochre-mongoose
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cyan-audemer.sh
        container: qc.met_squeaky-maroon-angelfish
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-champagne-vole.sh
        container: qc.sty_scummy-chartreuse-lemming
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-orange-tarsier.sh
        container: qc.sty_snippy-saffron-cuttlefish
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-scarlet-fish.sh
        container: qc.ver_freaky-lime-oriole
timeout: 5400
