config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ecru-ant.sh
        container: qc.acc_jumpy-rose-caiman
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-azure-kakapo.sh
        container: qc.doc_leaky-platinum-mastiff
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-magnolia-civet.sh
        container: qc.doc_ready-champagne-nightingale
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-scarlet-okapi.sh
        container: qc.doc_greasy-ecru-falcon
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-salmon-bison.sh
        container: qc.lic_cozy-thistle-lion
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-red-squirt.sh
        container: qc.met_blurry-pear-insect
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-beige-burmese.sh
        container: qc.sty_gummy-brass-gopher
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-smalt-beagle.sh
        container: qc.sty_greasy-crimson-robin
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-emerald-beetle.sh
        container: qc.ver_flaky-teal-eagle
timeout: 5400
