config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-bistre-manatee.sh
        container: qc.acc_cranky-black-shrew
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ecru-tuatara.sh
        container: qc.doc_wimpy-seashell-seahorse
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-orange-paradise.sh
        container: qc.doc_foggy-mustard-rattlesnake
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-green-angora.sh
        container: qc.doc_nerdy-periwinkle-coati
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-alizarin-chin.sh
        container: qc.lic_queasy-cinnabar-quoll
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-sepia-angora.sh
        container: qc.met_goopy-zucchini-cockroach
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ruby-cuscus.sh
        container: qc.sty_droopy-malachite-bombay
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-periwinkle-zonkey.sh
        container: qc.sty_lumpy-corn-coyote
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-chartreuse-insect.sh
        container: qc.ver_crabby-indigo-spider
timeout: 5400
