config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-sepia-gecko.sh
        container: qc.acc_beady-cobalt-wallaby
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-xanthic-eel.sh
        container: qc.doc_fuzzy-periwinkle-turkey
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-xanthic-chameleon.sh
        container: qc.doc_gummy-sapphire-wombat
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-wheat-butterfly.sh
        container: qc.doc_slaphappy-taupe-bear
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-buff-seahorse.sh
        container: qc.lic_flimsy-blue-cassowary
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-asparagus-bulldog.sh
        container: qc.met_leaky-rust-cassowary
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-carmine-chamois.sh
        container: qc.sty_snippy-brown-chow
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-khaki-vole.sh
        container: qc.sty_smelly-chocolate-tortoise
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-smalt-termite.sh
        container: qc.ver_crappy-ultramarine-setter
timeout: 5400
