config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-ruby-cuscus.sh
        container: qc.acc_randy-burgundy-greyhound
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-bronze-owl.sh
        container: qc.doc_breezy-mauve-foxhound
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-wheat-slug.sh
        container: qc.doc_snoopy-puce-cattle
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-olive-goat.sh
        container: qc.doc_silly-viridian-sloth
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-carmine-caterpillar.sh
        container: qc.lic_nippy-vermilion-duck
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-aquamarine-worm.sh
        container: qc.met_lovely-saffron-boar
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-green-bear.sh
        container: qc.sty_woolly-taupe-lemming
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-orchid-mammoth.sh
        container: qc.sty_silly-azure-barnacle
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-smalt-dhole.sh
        container: qc.ver_scaly-brass-toucan
timeout: 5400
