config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-goldenrod-audemer.sh
        container: qc.acc_tasty-cardinal-barracuda
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-sepia-ray.sh
        container: qc.doc_snoopy-lavender-turkey
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-razzmatazz-oyster.sh
        container: qc.doc_cozy-lime-cassowary
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-bronze-cockroach.sh
        container: qc.doc_zippy-yellow-javanese
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-ecru-avocet.sh
        container: qc.lic_cozy-puce-malamute
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-magenta-retriever.sh
        container: qc.met_ugly-lemon-whale
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-blue-moorhen.sh
        container: qc.sty_crabby-plum-leopard
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-turquoise-coyote.sh
        container: qc.sty_homely-amethyst-binturong
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-mustard-cuttlefish.sh
        container: qc.ver_sunny-salmon-ladybird
timeout: 5400
