config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-pink-crocodile.sh
        container: qc.acc_craggy-violet-olm
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-rose-flounder.sh
        container: qc.doc_clammy-cinnabar-hamster
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-magnolia-heron.sh
        container: qc.doc_droopy-aquamarine-javanese
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-saffron-earwig.sh
        container: qc.doc_thirsty-corn-rat
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-emerald-eleuth.sh
        container: qc.lic_crabby-amethyst-gharial
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homely-silver-crane.sh
        container: qc.met_paltry-persimmon-deer
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-heliotrope-clam.sh
        container: qc.sty_slaphappy-plum-camel
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-ecru-mandrill.sh
        container: qc.sty_skinny-saffron-crane
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cerulean-woodlouse.sh
        container: qc.ver_shabby-brass-cuscus
timeout: 5400
