config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-wheat-frog.sh
        container: qc.acc_fuzzy-asparagus-deer
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-corn-donkey.sh
        container: qc.doc_trippy-purple-affenpinscher
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-aqua-cougar.sh
        container: qc.doc_paltry-periwinkle-giraffe
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-saffron-coyote.sh
        container: qc.doc_shabby-auburn-mole
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-wisteria-bordeaux.sh
        container: qc.lic_droopy-pear-angelfish
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-eggplant-squirrel.sh
        container: qc.met_hasty-sepia-woodpecker
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ivory-bee.sh
        container: qc.sty_pasty-black-bonobo
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-orange-chipmunk.sh
        container: qc.sty_silly-yellow-emu
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-corn-bird.sh
        container: qc.ver_sleepy-jade-bonobo
timeout: 5400
