config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-brown-stoat.sh
        container: qc.acc_muggy-lime-quetzal
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-xanthic-dog.sh
        container: qc.doc_silly-viridian-fox
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-thistle-impala.sh
        container: qc.doc_flaky-maroon-uakari
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-auburn-crocodile.sh
        container: qc.doc_snippy-amaranth-forest
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cardinal-moose.sh
        container: qc.lic_flimsy-lavender-worm
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-champagne-bracke.sh
        container: qc.met_homey-cerulean-chimpanzee
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-goldenrod-dachsbracke.sh
        container: qc.sty_squeaky-blue-coati
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chestnut-cichlid.sh
        container: qc.sty_flabby-firebrick-cassowary
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-tomato-cuscus.sh
        container: qc.ver_blurry-chocolate-wildebeest
timeout: 5400
