config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-bistre-fowl.sh
        container: qc.acc_foggy-bistre-yak
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-thistle-monster.sh
        container: qc.doc_wimpy-teal-bonobo
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-magnolia-jackal.sh
        container: qc.doc_cozy-thistle-orangutan
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cerise-woodpecker.sh
        container: qc.doc_greasy-silver-pinscher
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-corn-axolotl.sh
        container: qc.lic_bluesy-indigo-sheep
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-saffron-buffalo.sh
        container: qc.met_sleepy-pear-mist
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-tomato-kiwi.sh
        container: qc.sty_nerdy-crimson-urchin
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-thistle-mule.sh
        container: qc.sty_lanky-indigo-rabbit
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-turquoise-discus.sh
        container: qc.ver_muzzy-corn-booby
timeout: 5400
