config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ruby-toad.sh
        container: qc.acc_foggy-violet-rattlesnake
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-plum-armadillo.sh
        container: qc.doc_queasy-emerald-javanese
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-crimson-audemer.sh
        container: qc.doc_pretty-sepia-camel
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-celadon-bison.sh
        container: qc.doc_gamy-wheat-spoonbill
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-pear-dog.sh
        container: qc.lic_lovely-auburn-weasel
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-corn-tamarin.sh
        container: qc.met_wimpy-azure-dachsbracke
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ecru-rabbit.sh
        container: qc.sty_clammy-taupe-slug
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-azure-chicken.sh
        container: qc.sty_cozy-cinnabar-forest
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-blue-fish.sh
        container: qc.ver_gamy-mustard-snake
timeout: 5400
