config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sepia-catfish.sh
        container: qc.acc_squeaky-red-spaniel
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-eggplant-bobcat.sh
        container: qc.doc_seedy-red-neanderthal
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-fuchsia-ray.sh
        container: qc.doc_cloudy-orchid-swan
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-myrtle-foxhound.sh
        container: qc.doc_homey-maroon-worm
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-plum-whale.sh
        container: qc.lic_skimpy-coral-mongrel
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-linen-birman.sh
        container: qc.met_greasy-vermilion-corgi
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-goldenrod-magpie.sh
        container: qc.sty_wiggy-seashell-flounder
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-goldenrod-ferret.sh
        container: qc.sty_tacky-xanthic-lizard
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-copper-lion.sh
        container: qc.ver_cheeky-mustard-orangutan
timeout: 5400
