config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-amber-fish.sh
        container: qc.acc_craggy-copper-frise
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-celadon-angelfish.sh
        container: qc.doc_messy-magenta-cheetah
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-ultramarine-llama.sh
        container: qc.doc_geeky-orchid-bee
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-firebrick-whippet.sh
        container: qc.doc_crappy-orange-dachshund
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-puce-llama.sh
        container: qc.lic_muzzy-ruby-bracke
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-white-retriever.sh
        container: qc.met_bumpy-puce-penguin
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-bistre-chinchilla.sh
        container: qc.sty_grumpy-apricot-collie
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cardinal-wrasse.sh
        container: qc.sty_bumpy-bronze-lemur
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ultramarine-kakapo.sh
        container: qc.ver_ready-plum-iguana
timeout: 5400
