config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cinnamon-capuchin.sh
        container: qc.acc_ugly-auburn-termite
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-emerald-wolf.sh
        container: qc.doc_homely-viridian-uguisu
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-harlequin-chicken.sh
        container: qc.doc_fuzzy-brown-otter
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-jade-bear.sh
        container: qc.doc_freaky-dandelion-corgi
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-pink-gorilla.sh
        container: qc.lic_muggy-buff-bullfrog
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-green-otter.sh
        container: qc.met_squirrely-cinnamon-mammoth
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-blue-chamois.sh
        container: qc.sty_sloppy-lilac-akbash
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-crimson-caiman.sh
        container: qc.sty_woozy-amaranth-bandicoot
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-olivine-reindeer.sh
        container: qc.ver_bumpy-saffron-beaver
timeout: 5400
