config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-malachite-dalmatian.sh
        container: qc.acc_wimpy-pear-chimpanzee
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-eggplant-ray.sh
        container: qc.doc_gamy-pear-uakari
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-flax-snail.sh
        container: qc.doc_snippy-champagne-toucan
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-saffron-mongoose.sh
        container: qc.doc_gummy-apricot-barracuda
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-amaranth-opossum.sh
        container: qc.lic_cozy-gamboge-mule
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ultramarine-ant.sh
        container: qc.met_paltry-sangria-coral
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-red-turkey.sh
        container: qc.sty_goopy-lilac-newfoundland
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-fuchsia-beetle.sh
        container: qc.sty_beady-myrtle-bracke
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-pumpkin-corgi.sh
        container: qc.ver_flimsy-mustard-reindeer
timeout: 5400
