config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-gold-mammoth.sh
        container: qc.acc_gimpy-rust-goat
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-russet-orangutan.sh
        container: qc.doc_snoopy-harlequin-paradise
      github.com/eosc-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-gold-boar.sh
        container: qc.doc_lanky-dandelion-chamois
      github.com/eosc-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-lilac-dragonfly.sh
        container: qc.doc_stinky-amethyst-havanese
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chocolate-dodo.sh
        container: qc.lic_pokey-aqua-woodpecker
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-thistle-octopus.sh
        container: qc.met_baggy-crimson-dhole
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-ruby-pinscher.sh
        container: qc.sty_paltry-corn-spitz
      github.com/eosc-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pink-gerbil.sh
        container: qc.sty_greasy-buff-catfish
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-denim-newt.sh
        container: qc.ver_whiny-harlequin-crocodile
timeout: 5400
