config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-periwinkle-deer.sh
        container: qc.acc_ugly-periwinkle-balinese
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cerise-cat.sh
        container: qc.doc_fuzzy-sapphire-starfish
      github.com/EOSC-synergy/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-maroon-meerkat.sh
        container: qc.doc_skinny-charcoal-dachshund
      github.com/EOSC-synergy/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-russet-chinook.sh
        container: qc.doc_randy-carmine-markhor
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-thistle-fish.sh
        container: qc.lic_chummy-amethyst-dog
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-amber-serval.sh
        container: qc.met_squirrely-violet-sparrow
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-coral-slug.sh
        container: qc.sty_thirsty-corn-heron
      github.com/EOSC-synergy/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-persimmon-jaguar.sh
        container: qc.sty_foggy-magenta-barb
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-viridian-llama.sh
        container: qc.ver_slaphappy-pumpkin-dragonfly
timeout: 5400
