config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/sqaaas-web:
      branch: master
      repo: https://github.com/darce-i3m/sqaaas-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-charcoal-dragon.sh
        container: qc.acc_messy-tomato-husky
  QC.Doc:
    repos:
      github.com/darce-i3m/sqaaas-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-turquoise-kangaroo.sh
        container: qc.doc_randy-charcoal-mule
      github.com/darce-i3m/sqaaas-web git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-ultramarine-jaguar.sh
        container: qc.doc_cloudy-lemon-bison
      github.com/darce-i3m/sqaaas-web markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-magenta-dog.sh
        container: qc.doc_tasty-buff-starfish
  QC.Lic:
    repos:
      github.com/darce-i3m/sqaaas-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-tomato-squirrel.sh
        container: qc.lic_tasty-red-ocelot
  QC.Met:
    repos:
      github.com/darce-i3m/sqaaas-web cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-denim-rabbit.sh
        container: qc.met_sloppy-white-ferret
  QC.Sty:
    repos:
      github.com/darce-i3m/sqaaas-web hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-flax-wombat.sh
        container: qc.sty_wheezy-brass-caracal
      github.com/darce-i3m/sqaaas-web jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-harlequin-mouse.sh
        container: qc.sty_droopy-eggplant-greyhound
  QC.Ver:
    repos:
      github.com/darce-i3m/sqaaas-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-red-sparrow.sh
        container: qc.ver_ready-amber-indri
timeout: 5400
